version: '3.8'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: hbadmin
      POSTGRES_PASSWORD: password
      POSTGRES_MULTIPLE_DATABASES: hungerbox_identity,hungerbox_orders,hungerbox_vendor,hungerbox_payment,hungerbox_wallet,hungerbox_inventory,hungerbox_menu,sonarqube
    volumes:
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  discovery-server:
    build: ./backend/discovery-server
    environment:
      - SPRING_PROFILES_ACTIVE=prod

  config-server:
    build: ./backend/config-server
    depends_on:
      - discovery-server
    environment:
      - SPRING_PROFILES_ACTIVE=prod

  api-gateway:
    build: ./backend/api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - config-server
    environment:
      - SPRING_PROFILES_ACTIVE=prod

  identity:
    build: ./backend/identity
    depends_on:
      - postgres
      - config-server
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - CONFIG_SERVER_URL=http://config-server:8888

  order-service:
    build: ./backend/order-service
    depends_on:
      - postgres
      - config-server
    environment:
      - SPRING_PROFILES_ACTIVE=prod

  vendor-service:
    build: ./backend/vendor-service
    depends_on:
      - postgres
      - config-server
    environment:
      - SPRING_PROFILES_ACTIVE=prod

  ## newly added service start
  menu-service:
    build: ./backend/menu-service
    depends_on:
      - postgres
      - config-server
    environment:
      - SPRING_PROFILES_ACTIVE=prod

  inventory-service:
    build: ./backend/inventory-service
    depends_on:
      - postgres
      - config-server
    environment:
      - SPRING_PROFILES_ACTIVE=prod

  wallet-service:
    build: ./backend/wallet-service
    depends_on:
      - postgres
      - config-server
    environment:
      - SPRING_PROFILES_ACTIVE=prod

  payment-service:
    build: ./backend/payment-service
    depends_on:
      - postgres
      - config-server
    environment:
      - SPRING_PROFILES_ACTIVE=prod
   ## newly added service end
   
  frontend:
    build:
      context: ./frontend
      args:
        - VITE_API_BASE_URL=http://localhost:8080
    ports:
      - "3000:80"
    depends_on:
      - api-gateway

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"

  sonarqube:
      image: sonarqube:community
      container_name: sonarqube
      depends_on:
        - postgres
      ports:
        - "9000:9000"
      environment:
        # We connect to your existing 'postgres' service
        # Note: inside the docker network, we use port 5432, not the mapped 5433
        - SONAR_JDBC_URL=jdbc:postgresql://postgres:5432/sonarqube
        - SONAR_JDBC_USERNAME=hbadmin
        - SONAR_JDBC_PASSWORD=password
      volumes:
        - sonarqube_data:/opt/sonarqube/data
        - sonarqube_extensions:/opt/sonarqube/extensions
        - sonarqube_logs:/opt/sonarqube/logs

  volumes:
  postgres_data:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs: